# steps:
#   # 1. Build Backend Image
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'gcr.io/$PROJECT_ID/api-backend', '-f', 'Dockerfile-backend', '.']

#   # 2. Build Frontend Image
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'gcr.io/$PROJECT_ID/angular-frontend', '-f', 'Dockerfile-frontend', '.']

#   # 3. Push Images to Container Registry
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'gcr.io/$PROJECT_ID/api-backend']
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'gcr.io/$PROJECT_ID/angular-frontend']

# images:
#   - 'gcr.io/$PROJECT_ID/api-backend'
#   - 'gcr.io/$PROJECT_ID/angular-frontend'
# options:
#   logging: CLOUD_LOGGING_ONLY


steps:
  # Step 1: Build the Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend-service-test', '-f', 'Dockerfile-backend', '.']

  # Step 2: Push the Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend-service-test']

  # Step 3: Deploy the Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'backend-service-test'
      - '--image=gcr.io/$PROJECT_ID/backend-service-test'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

  # Step 4: Build the Frontend Image
  # Note: Ensure your Dockerfile-frontend correctly builds the Angular app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend-service-test', '-f', 'Dockerfile-frontend', '.']

  # Step 5: Push the Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend-service-test']

  # Step 6: Deploy the Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'frontend-service-test'
      - '--image=gcr.io/$PROJECT_ID/frontend-service-test'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/backend-service-test'
  - 'gcr.io/$PROJECT_ID/frontend-service-test'

options:
  logging: CLOUD_LOGGING_ONLY
