# steps:
#   # 1. Build Backend Image
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'gcr.io/$PROJECT_ID/api-backend', '-f', 'Dockerfile-backend', '.']

#   # 2. Build Frontend Image
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'gcr.io/$PROJECT_ID/angular-frontend', '-f', 'Dockerfile-frontend', '.']

#   # 3. Push Images to Container Registry
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'gcr.io/$PROJECT_ID/api-backend']
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'gcr.io/$PROJECT_ID/angular-frontend']

# images:
#   - 'gcr.io/$PROJECT_ID/api-backend'
#   - 'gcr.io/$PROJECT_ID/angular-frontend'
# options:
#   logging: CLOUD_LOGGING_ONLY

# #front-end -successful
# steps:
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend-service-test', '-f', 'Dockerfile-frontend', '.']

#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'gcr.io/$PROJECT_ID/frontend-service-test']

#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     entrypoint: gcloud
#     args:
#       - 'run'
#       - 'deploy'
#       - 'frontend-service-test'
#       - '--image=gcr.io/$PROJECT_ID/frontend-service-test'
#       - '--region=us-central1'
#       - '--platform=managed'
#       - '--port=8080'  # <--- CRITICAL: Tells Cloud Run to check 8080
#       - '--allow-unauthenticated'


# options:
#   logging: CLOUD_LOGGING_ONLY


steps:
  # Build the Test Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend-service-test', '-f', 'Dockerfile-backend', '.']

  # Push the Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend-service-test']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'backend-service-test'
      - '--image=gcr.io/$PROJECT_ID/backend-service-test'
      - '--region=us-central1'
      - '--platform=managed'
      - '--port=8080'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/backend-service-test'
options:
   logging: CLOUD_LOGGING_ONLY
