steps:
  # 1. Build the Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/api-backend', '-f', 'Dockerfile-backend', '.']

  # 2. Build the Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/angular-frontend', '-f', 'Dockerfile-frontend', '.']

  # 3. Push Backend Image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/api-backend']

  # 4. Push Frontend Image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/angular-frontend']

  # 5. Deploy Backend to Cloud Run
  # This fixes the port issue by explicitly setting it to 8080 and passing the required GCP Key
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'api-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/api-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GCP_SERVICE_ACCOUNT_KEY=${_GCP_SERVICE_ACCOUNT_KEY}'

  # 6. Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'angular-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/angular-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/api-backend'
  - 'gcr.io/$PROJECT_ID/angular-frontend'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _GCP_SERVICE_ACCOUNT_KEY: 'default_placeholder_or_real_key_string'
