FROM node:lts-alpine AS frontend-build
WORKDIR /app
COPY package*.json ./
RUN npm install --silent
COPY . .
RUN npm run build -- --configuration=production --base-href=/

FROM nginx:alpine

# CRITICAL STEP: Copy the custom nginx.conf into the container
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the built Angular files
COPY --from=frontend-build /app/dist/tsr/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
